version: '3'
services:
  neo4j:
    image: neo4j:4.4-community
    hostname: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j-data:/data
      - neo4j-plugins:/plugins
volumes:
  neo4j-data:
  neo4j-plugins:

networks: 
  default: 
    external: 
      name: database

