version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        - rabbitmq-log:/var/log/rabbitmq
        # - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config

volumes:
  rabbitmq-data:
  rabbitmq-log:

networks: 
  default: 
    external: 
      name: database