version: '3'
services:
  db2server:
    privileged: true
    image: icr.io/db2_community/db2
    restart: always
    container_name: db2server
    ports: 
      - "50000:50000"
    environment:
      - LICENSE=accept
      - DB2INSTANCE=db2inst1
      - DB2INST1_PASSWORD=password
      - DBNAME=testdb
      - BLU=false
      - ENABLE_ORACLE_COMPATIBILITY=false
      - UPDATEAVAIL=NO
      - TO_CREATE_SAMPLEDB=false
      - REPODB=false
      - IS_OSXFS=false
      - PERSISTENT_HOME=true
      - HADR_ENABLED=false
      - ETCD_ENDPOINT=
      - ETCD_USERNAME=
      - ETCD_PASSWORD=
    volumes:
      - db2-data:/database
volumes:
  db2-data:

networks:
  default:
    name: database
    external: true