FEATURE_FLAGS = { 
    'DASHBOARD_CROSS_FILTERS': True,
    'DASHBOARD_RBAC': True,
    'ESCAPE_MARKDOWN_HTML': True,
    'ENABLE_TEMPLATE_PROCESSING': True,
    'LISTVIEWS_DEFAULT_CARD_VIEW': True,
    'SCHEDULED_QUERIES': True,
    'SQL_VALIDATORS_BY_ENGINE': True,
    'SQLLAB_BACKEND_PERSISTENCE': True,
    'THUMBNAILS': True,
}