version: '3'
services:
  db:
    image: mariadb:10
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mariadb-data:/var/lib/mysql
volumes:
  mariadb-data:

networks:
  default:
    name: database
    external: true
