version: '3'
services:
  julia:
    image: rochimfn/juliadb-notebook:1.7.1
    ports:
      - "8888:8888"
    volumes:
      - julia-data:/home/rochim/data
      - ./shared:/home/rochim/shared
    entrypoint: sh -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser
      --notebook-dir=/home/rochim/data --NotebookApp.token=''
      --NotebookApp.password=''"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: 2
    #       memory: 1g

volumes:
  julia-data:

networks:
  default:
    external:
      name: database
