version: '3'
services:
  zeppelin:
    image: apache/zeppelin:0.10.0
    hostname: zeppelin
    restart: always
    ports:
      - 8080:8080
      - 4040:4040
    volumes:
      - conf:/opt/zeppelin/conf
      - logs:/opt/zeppelin/logs
      - notebook:/opt/zeppelin/notebook
      - repo:/opt/zeppelin/local-repo
    environment:
      - ZEPPELIN_NOTEBOOK_CRON_ENABLE=true
      - ZEPPELIN_METRIC_ENABLE_PROMETHEUS=true

volumes:
  conf:
    driver: local
  logs:
    driver: local
  notebook:
    driver: local
  repo:
    driver: local

networks:
  default:
    external:
      name: database
