version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4:4.29
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=rochim@localhost
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8060:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    depends_on: 
      - db
  db:
    image: postgres:10
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
      - postgres-backup:/backups
volumes:
  postgres-data:
  postgres-backup:
  pgadmin-data:

networks: 
  default: 
    external: 
      name: database

