services:
  influxdb:
    image: influxdb:2
    restart: always
    ports: 
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influx
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=local
      - DOCKER_INFLUXDB_INIT_BUCKET=default
    volumes:
      - influx-data:/var/lib/influxdb2
      - influx-config:/etc/influxdb2
volumes:
  influx-data:
  influx-config:

networks:
  default:
    name: database
    external: true
